name: scgeo-gse211713-dataset-c
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - psutil
  - ipykernel
  - nbclient
  - nbformat
  - pyyaml
  - scikit-image=0.25.2
  - pip:
      - scrublet==0.2.3
